plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.springai'
version = '0.0.1-SNAPSHOT'
description = 'Generative AI project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "1.1.2")
}

dependencies {

    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // Spring AI with Google Gemini Support
//    implementation 'org.springframework.ai:spring-ai-google-ai-spring-boot-starter:0.8.1'
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'

    // Lombok for reducing boilerplate
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // JSON Processing
    implementation 'com.google.code.gson:gson:2.10.1'

    // Jackson for JSON serialization
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    //springdoc-openapi
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    // Testing
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

springBoot {
    buildInfo()
}